// export const players = [
//   {
//     id: 1,
//     fullName: "Marcus Bennett",
//     position: "SG",
//     rarity: "Superstar",
//     offensiveRating: 91,
//     defensiveRating: 88,
//     overallRating: 90,
//     image: "player1",
//   },
//   {
//     id: 2,
//     fullName: "Ethan Cole",
//     position: "PG",
//     rarity: "Common",
//     offensiveRating: 58,
//     defensiveRating: 61,
//     overallRating: 60,
//     image: "player2",
//   },
//   {
//     id: 3,
//     fullName: "Andre Mitchell",
//     position: "PF",
//     rarity: "Rare",
//     offensiveRating: 76,
//     defensiveRating: 81,
//     overallRating: 79,
//     image: "player3",
//   },
//   {
//     id: 4,
//     fullName: "Darius Hayes",
//     position: "C",
//     rarity: "Common",
//     offensiveRating: 97,
//     defensiveRating: 96,
//     overallRating: 97,
//     image: "player4",
//   },
//   {
//     id: 5,
//     fullName: "Julian Brooks",
//     position: "SF",
//     rarity: "Common",
//     offensiveRating: 64,
//     defensiveRating: 57,
//     overallRating: 61,
//     image: "player5",
//   },
//   {
//     id: 6,
//     fullName: "Malik Foster",
//     position: "PG",
//     rarity: "Rare",
//     offensiveRating: 73,
//     defensiveRating: 78,
//     overallRating: 76,
//     image: "player6",
//   },
//   {
//     id: 7,
//     fullName: "Caleb Turner",
//     position: "SG",
//     rarity: "Superstar",
//     offensiveRating: 87,
//     defensiveRating: 91,
//     overallRating: 89,
//     image: "player7",
//   },
//   {
//     id: 8,
//     fullName: "Isaiah Morgan",
//     position: "C",
//     rarity: "Legendary",
//     offensiveRating: 52,
//     defensiveRating: 59,
//     overallRating: 56,
//     image: "player8",
//   },
//   {
//     id: 9,
//     fullName: "Jalen Richardson",
//     position: "SF",
//     rarity: "Rare",
//     offensiveRating: 82,
//     defensiveRating: 75,
//     overallRating: 79,
//     image: "player9",
//   },
//   {
//     id: 10,
//     fullName: "Noah Williams",
//     position: "PF",
//     rarity: "Common",
//     offensiveRating: 66,
//     defensiveRating: 63,
//     overallRating: 65,
//     image: "player10",
//   },
//   {
//     id: 11,
//     fullName: "Terrence Price",
//     position: "PG",
//     rarity: "Superstar",
//     offensiveRating: 94,
//     defensiveRating: 90,
//     overallRating: 92,
//     image: "player11",
//   },
//   {
//     id: 12,
//     fullName: "Liam Carter",
//     position: "SG",
//     rarity: "Rare",
//     offensiveRating: 71,
//     defensiveRating: 74,
//     overallRating: 73,
//     image: "player12",
//   },
//   {
//     id: 13,
//     fullName: "Devin Parker",
//     position: "C",
//     rarity: "Common",
//     offensiveRating: 55,
//     defensiveRating: 67,
//     overallRating: 61,
//     image: "player13",
//   },
//   {
//     id: 14,
//     fullName: "Marcus Reed",
//     position: "SF",
//     rarity: "Superstar",
//     offensiveRating: 86,
//     defensiveRating: 89,
//     overallRating: 88,
//     image: "player14",
//   },
//   {
//     id: 15,
//     fullName: "Jordan Ellis",
//     position: "PF",
//     rarity: "Rare",
//     offensiveRating: 79,
//     defensiveRating: 83,
//     overallRating: 81,
//     image: "player15",
//   },
//   {
//     id: 16,
//     fullName: "Cameron Davis",
//     position: "SG",
//     rarity: "Common",
//     offensiveRating: 62,
//     defensiveRating: 54,
//     overallRating: 58,
//     image: "player16",
//   },
//   {
//     id: 17,
//     fullName: "Xavier Thompson",
//     position: "PG",
//     rarity: "Legendary",
//     offensiveRating: 99,
//     defensiveRating: 97,
//     overallRating: 98,
//     image: "player17",
//   },
//   {
//     id: 18,
//     fullName: "Anthony Green",
//     position: "SF",
//     rarity: "Rare",
//     offensiveRating: 77,
//     defensiveRating: 72,
//     overallRating: 75,
//     image: "player18",
//   },
//   {
//     id: 19,
//     fullName: "Brandon Scott",
//     position: "C",
//     rarity: "Common",
//     offensiveRating: 60,
//     defensiveRating: 65,
//     overallRating: 63,
//     image: "player19",
//   },
//   {
//     id: 20,
//     fullName: "Damian Wright",
//     position: "SG",
//     rarity: "Superstar",
//     offensiveRating: 92,
//     defensiveRating: 94,
//     overallRating: 93,
//     image: "player20",
//   },
//   {
//     id: 21,
//     fullName: "Tyler Adams",
//     position: "PF",
//     rarity: "Rare",
//     offensiveRating: 84,
//     defensiveRating: 80,
//     overallRating: 82,
//     image: "player21",
//   },
//   {
//     id: 22,
//     fullName: "Jayden Moore",
//     position: "SG",
//     rarity: "Common",
//     offensiveRating: 57,
//     defensiveRating: 62,
//     overallRating: 60,
//     image: "player22",
//   },
//   {
//     id: 23,
//     fullName: "Dominic King",
//     position: "C",
//     rarity: "Superstar",
//     offensiveRating: 89,
//     defensiveRating: 86,
//     overallRating: 88,
//     image: "player23",
//   },
//   {
//     id: 24,
//     fullName: "Chris Johnson",
//     position: "SF",
//     rarity: "Common",
//     offensiveRating: 69,
//     defensiveRating: 64,
//     overallRating: 67,
//     image: "player24",
//   },
//   {
//     id: 25,
//     fullName: "Raymond Brooks",
//     position: "PG",
//     rarity: "Rare",
//     offensiveRating: 74,
//     defensiveRating: 82,
//     overallRating: 78,
//     image: "player25",
//   },
//   {
//     id: 26,
//     fullName: "Dylan Harris",
//     position: "PF",
//     rarity: "Common",
//     offensiveRating: 53,
//     defensiveRating: 58,
//     overallRating: 56,
//     image: "player26",
//   },
//   {
//     id: 27,
//     fullName: "Kendrick Lewis",
//     position: "SG",
//     rarity: "Superstar",
//     offensiveRating: 90,
//     defensiveRating: 93,
//     overallRating: 92,
//     image: "player27",
//   },
//   {
//     id: 28,
//     fullName: "Nathan Walker",
//     position: "C",
//     rarity: "Rare",
//     offensiveRating: 81,
//     defensiveRating: 77,
//     overallRating: 79,
//     image: "player28",
//   },
//   {
//     id: 29,
//     fullName: "Aaron Collins",
//     position: "SF",
//     rarity: "Common",
//     offensiveRating: 61,
//     defensiveRating: 56,
//     overallRating: 59,
//     image: "player29",
//   },
//   {
//     id: 30,
//     fullName: "Jeremiah Davis",
//     position: "PG",
//     rarity: "Rare",
//     offensiveRating: 72,
//     defensiveRating: 79,
//     overallRating: 76,
//     image: "player30",
//   },
//   {
//     id: 31,
//     fullName: "Kobe Warren",
//     position: "SG",
//     rarity: "Common",
//     offensiveRating: 53,
//     defensiveRating: 55,
//     overallRating: 54,
//     image: "player31",
//   },
//   {
//     id: 32,
//     fullName: "Marcus Young",
//     position: "PF",
//     rarity: "Superstar",
//     offensiveRating: 88,
//     defensiveRating: 92,
//     overallRating: 90,
//     image: "player32",
//   },
//   {
//     id: 33,
//     fullName: "Elijah Carter",
//     position: "C",
//     rarity: "Rare",
//     offensiveRating: 83,
//     defensiveRating: 78,
//     overallRating: 81,
//     image: "player33",
//   },
//   {
//     id: 34,
//     fullName: "Brayden Hill",
//     position: "SF",
//     rarity: "Common",
//     offensiveRating: 65,
//     defensiveRating: 68,
//     overallRating: 67,
//     image: "player34",
//   },
//   {
//     id: 35,
//     fullName: "Isaac Bryant",
//     position: "PG",
//     rarity: "Rare",
//     offensiveRating: 75,
//     defensiveRating: 80,
//     overallRating: 78,
//     image: "player35",
//   },
//   {
//     id: 36,
//     fullName: "Darius Coleman",
//     position: "PF",
//     rarity: "Legendary",
//     offensiveRating: 96,
//     defensiveRating: 99,
//     overallRating: 98,
//     image: "player36",
//   },
//   {
//     id: 37,
//     fullName: "Logan Mitchell",
//     position: "SG",
//     rarity: "Common",
//     offensiveRating: 59,
//     defensiveRating: 63,
//     overallRating: 61,
//     image: "player37",
//   },
//   {
//     id: 38,
//     fullName: "Mason Anderson",
//     position: "C",
//     rarity: "Superstar",
//     offensiveRating: 85,
//     defensiveRating: 91,
//     overallRating: 88,
//     image: "player38",
//   },
//   {
//     id: 39,
//     fullName: "Carter Wilson",
//     position: "SG",
//     rarity: "Rare",
//     offensiveRating: 80,
//     defensiveRating: 84,
//     overallRating: 82,
//     image: "player39",
//   },
//   {
//     id: 40,
//     fullName: "Derek Thomas",
//     position: "SF",
//     rarity: "Common",
//     offensiveRating: 56,
//     defensiveRating: 60,
//     overallRating: 58,
//     image: "player40",
//   },
//   {
//     id: 41,
//     fullName: "Jaylen Cooper",
//     position: "PG",
//     rarity: "Superstar",
//     offensiveRating: 93,
//     defensiveRating: 87,
//     overallRating: 90,
//     image: "player41",
//   },
//   {
//     id: 42,
//     fullName: "Michael Edwards",
//     position: "PF",
//     rarity: "Rare",
//     offensiveRating: 78,
//     defensiveRating: 83,
//     overallRating: 81,
//     image: "player42",
//   },
//   {
//     id: 43,
//     fullName: "Robert Turner",
//     position: "C",
//     rarity: "Common",
//     offensiveRating: 51,
//     defensiveRating: 64,
//     overallRating: 58,
//     image: "player43",
//   },
//   {
//     id: 44,
//     fullName: "Trevor Martin",
//     position: "SG",
//     rarity: "Rare",
//     offensiveRating: 76,
//     defensiveRating: 73,
//     overallRating: 75,
//     image: "player44",
//   },
//   {
//     id: 45,
//     fullName: "Damien Foster",
//     position: "SF",
//     rarity: "Superstar",
//     offensiveRating: 91,
//     defensiveRating: 95,
//     overallRating: 93,
//     image: "player45",
//   },
//   {
//     id: 46,
//     fullName: "Cameron Brooks",
//     position: "PG",
//     rarity: "Common",
//     offensiveRating: 63,
//     defensiveRating: 57,
//     overallRating: 60,
//     image: "player46",
//   },
//   {
//     id: 47,
//     fullName: "Jamal Richardson",
//     position: "PF",
//     rarity: "Rare",
//     offensiveRating: 82,
//     defensiveRating: 76,
//     overallRating: 79,
//     image: "player47",
//   },
//   {
//     id: 48,
//     fullName: "Landon Price",
//     position: "C",
//     rarity: "Common",
//     offensiveRating: 67,
//     defensiveRating: 69,
//     overallRating: 68,
//     image: "player48",
//   },
//   {
//     id: 49,
//     fullName: "Malcolm Hayes",
//     position: "SG",
//     rarity: "Legendary",
//     offensiveRating: 98,
//     defensiveRating: 95,
//     overallRating: 97,
//     image: "player49",
//   },
//   {
//     id: 50,
//     fullName: "Owen Parker",
//     position: "SF",
//     rarity: "Common",
//     offensiveRating: 54,
//     defensiveRating: 62,
//     overallRating: 58,
//     image: "player50",
//   },
//   {
//     id: 51,
//     fullName: "Zachary Reed",
//     position: "PG",
//     rarity: "Rare",
//     offensiveRating: 73,
//     defensiveRating: 81,
//     overallRating: 77,
//     image: "player51",
//   },
//   {
//     id: 52,
//     fullName: "Andre Williams",
//     position: "PF",
//     rarity: "Superstar",
//     offensiveRating: 87,
//     defensiveRating: 90,
//     overallRating: 89,
//     image: "player52",
//   },
//   {
//     id: 53,
//     fullName: "Evan Mitchell",
//     position: "C",
//     rarity: "Common",
//     offensiveRating: 58,
//     defensiveRating: 66,
//     overallRating: 62,
//     image: "player53",
//   },
//   {
//     id: 54,
//     fullName: "Jared Thompson",
//     position: "SG",
//     rarity: "Rare",
//     offensiveRating: 84,
//     defensiveRating: 79,
//     overallRating: 82,
//     image: "player54",
//   },
//   {
//     id: 55,
//     fullName: "Tristan Morgan",
//     position: "SF",
//     rarity: "Common",
//     offensiveRating: 62,
//     defensiveRating: 68,
//     overallRating: 65,
//     image: "player55",
//   },
//   {
//     id: 56,
//     fullName: "Dante Robinson",
//     position: "PG",
//     rarity: "Superstar",
//     offensiveRating: 95,
//     defensiveRating: 89,
//     overallRating: 92,
//     image: "player56",
//   },
//   {
//     id: 57,
//     fullName: "Hunter Collins",
//     position: "PF",
//     rarity: "Common",
//     offensiveRating: 55,
//     defensiveRating: 61,
//     overallRating: 58,
//     image: "player57",
//   },
//   {
//     id: 58,
//     fullName: "Kenneth Davis",
//     position: "C",
//     rarity: "Rare",
//     offensiveRating: 77,
//     defensiveRating: 82,
//     overallRating: 80,
//     image: "player58",
//   },
//   {
//     id: 59,
//     fullName: "Adrian Washington",
//     position: "SG",
//     rarity: "Common",
//     offensiveRating: 69,
//     defensiveRating: 65,
//     overallRating: 67,
//     image: "player59",
//   },
//   {
//     id: 60,
//     fullName: "Xavier Johnson",
//     position: "SF",
//     rarity: "Legendary",
//     offensiveRating: 97,
//     defensiveRating: 98,
//     overallRating: 98,
//     image: "player60",
//   },
// ];
